### ISSUE TITLE
Demo page needs a new video

### ISSUE THREAD

**Issue by tony** [contently/videojs-annotation-comments#66] opened 2020-05-06 23:04 UTC
Hi, thank you for the project!  Example info needs to be updated in the demo

https://contently.github.io/videojs-annotation-comments/

https://s3.amazonaws.com/misc-files-bucket/arethusa-cheese-short.mp4 / `NoSuchBucket`

Know anything it could be replaced with? (or reuploaded somewhere if someone still has it?)

**Comment by jackpope** [comment] 2020-05-07 00:20
Hi @tony thanks for adding the issue here. It's actually a duplicate of https://github.com/contently/videojs-annotation-comments/issues/59 so I'll close this one for now. Should be fixed with https://github.com/contently/videojs-annotation-comments/pull/63

**Closed by jackpope** 2020-05-07 00:20 UTC

**Comment by tony** [comment] 2020-05-07 01:38
@jackpope Nice!

https://contently.github.io/videojs-annotation-comments/ looks fantastic!
